@extends('layouts.app')
@section('post_list')
<x-post-view/>
<x-post-view/>
<x-post-view/>
<x-post-view/>
<x-post-view/>
<x-post-view/>
<x-post-view/>
{{$post_id}}
@endsection
@section('comment_list')
<x-comment-view/>
<x-comment-view/>
<x-comment-view/>
<x-comment-view/>
<x-comment-view/>
<x-comment-view/>
<x-comment-view/>
@endsection
